#include "stm32f1xx_it.h"
#include "stm32f1xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"
void xPortSysTickHandler(void);
void SysTick_Handler(void)
{
    /* One HAL millisecond before and after scheduler start; tick hook stays disabled. */
    HAL_IncTick();
    if (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED) {
        xPortSysTickHandler();
    }
}
/* SVC/PendSV are defined directly by port.c using FreeRTOSConfig aliases.
 * TO DO: route each enabled peripheral IRQ to its module owner before enabling it.
 * Traps are bring-up diagnostics, not the final fault-handling implementation.
 */
#define UNIMPLEMENTED_IRQ(name) void name(void) { configASSERT(0); }
UNIMPLEMENTED_IRQ(NMI_Handler)
UNIMPLEMENTED_IRQ(HardFault_Handler)
UNIMPLEMENTED_IRQ(MemManage_Handler)
UNIMPLEMENTED_IRQ(BusFault_Handler)
UNIMPLEMENTED_IRQ(UsageFault_Handler)
UNIMPLEMENTED_IRQ(DebugMon_Handler)
UNIMPLEMENTED_IRQ(WWDG_IRQHandler)
UNIMPLEMENTED_IRQ(PVD_IRQHandler)
UNIMPLEMENTED_IRQ(TAMPER_IRQHandler)
UNIMPLEMENTED_IRQ(RTC_IRQHandler)
UNIMPLEMENTED_IRQ(FLASH_IRQHandler)
UNIMPLEMENTED_IRQ(RCC_IRQHandler)
UNIMPLEMENTED_IRQ(EXTI0_IRQHandler)
UNIMPLEMENTED_IRQ(EXTI1_IRQHandler)
UNIMPLEMENTED_IRQ(EXTI2_IRQHandler)
UNIMPLEMENTED_IRQ(EXTI3_IRQHandler)
UNIMPLEMENTED_IRQ(EXTI4_IRQHandler)
UNIMPLEMENTED_IRQ(DMA1_Channel1_IRQHandler)
UNIMPLEMENTED_IRQ(DMA1_Channel2_IRQHandler)
UNIMPLEMENTED_IRQ(DMA1_Channel3_IRQHandler)
UNIMPLEMENTED_IRQ(DMA1_Channel4_IRQHandler)
UNIMPLEMENTED_IRQ(DMA1_Channel5_IRQHandler)
UNIMPLEMENTED_IRQ(DMA1_Channel6_IRQHandler)
UNIMPLEMENTED_IRQ(DMA1_Channel7_IRQHandler)
UNIMPLEMENTED_IRQ(ADC1_2_IRQHandler)
UNIMPLEMENTED_IRQ(USB_HP_CAN1_TX_IRQHandler)
UNIMPLEMENTED_IRQ(USB_LP_CAN1_RX0_IRQHandler)
UNIMPLEMENTED_IRQ(CAN1_RX1_IRQHandler)
UNIMPLEMENTED_IRQ(CAN1_SCE_IRQHandler)
UNIMPLEMENTED_IRQ(EXTI9_5_IRQHandler)
UNIMPLEMENTED_IRQ(TIM1_BRK_IRQHandler)
UNIMPLEMENTED_IRQ(TIM1_UP_IRQHandler)
UNIMPLEMENTED_IRQ(TIM1_TRG_COM_IRQHandler)
UNIMPLEMENTED_IRQ(TIM1_CC_IRQHandler)
UNIMPLEMENTED_IRQ(TIM2_IRQHandler)
UNIMPLEMENTED_IRQ(TIM3_IRQHandler)
UNIMPLEMENTED_IRQ(TIM4_IRQHandler)
UNIMPLEMENTED_IRQ(I2C1_EV_IRQHandler)
UNIMPLEMENTED_IRQ(I2C1_ER_IRQHandler)
UNIMPLEMENTED_IRQ(I2C2_EV_IRQHandler)
UNIMPLEMENTED_IRQ(I2C2_ER_IRQHandler)
UNIMPLEMENTED_IRQ(SPI1_IRQHandler)
UNIMPLEMENTED_IRQ(SPI2_IRQHandler)
UNIMPLEMENTED_IRQ(USART1_IRQHandler)
UNIMPLEMENTED_IRQ(USART2_IRQHandler)
UNIMPLEMENTED_IRQ(USART3_IRQHandler)
UNIMPLEMENTED_IRQ(EXTI15_10_IRQHandler)
UNIMPLEMENTED_IRQ(RTC_Alarm_IRQHandler)
UNIMPLEMENTED_IRQ(USBWakeUp_IRQHandler)
